version: 0.2

env:
  vars:
    NODE_ENV: production

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm i -g yarn
      - yarn
  build:
    commands:
      - yarn run build
  post_build:
    commands:
      - aws s3 sync --delete build/ s3://$STATIC_ASSETS_BUCKET 
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION --paths "/*"



