[build]
  command = "yarn build"
  publish = "out"

[context.production]
  environment = { NETLIFY_NEXT_PLUGIN_SKIP = true }

[[redirects]]
  from = "https://makeprogramming.fun/*"
  to = "https://moroz.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.makeprogramming.fun/*"
  to = "https://moroz.dev/:splat"
  status = 301
  force = true

[[plugins]]
  package = "@netlify/plugin-nextjs"
